#!/bin/bash

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

if ! command_exists brew; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

brew bundle install --no-lock --no-upgrade

ln -s -i "$(pwd)"/zshrc ~/.zshrc
ln -s -i "$(pwd)"/vimrc ~/.vimrc
ln -s -i -n "$(pwd)"/vim ~/.vim
ln -s -i "$(pwd)"/gitconfig ~/.gitconfig

vim -c PlugInstall -c qa!

