#!/bin/bash

cmd_exists() {
    command -v "$1" >/dev/null 2>&1
}

create_symlinks() {
    local dotfile
    for dotfile in zshrc vimrc vim gitconfig; do
	    ln -sin {$(pwd)/,~/.}"${dotfile}"
    done
}

create_symlinks

if cmd_exists brew; then
    brew bundle install --no-lock --no-upgrade
else
    echo "Homebrew is not in the search path. Skipping installation of packages."
fi

git submodule init
git submodule update

mkdir -p vim/autoload
cp vim-plug/plug.vim vim/autoload
mkdir -p vim/colors
cp molokai/colors/molokai.vim vim/colors

if cmd_exists vim; then
    vim -c PlugInstall -c qa!
else
    echo "Vim is not in the search path. Skipping installation of plugins."
fi

